global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configurations
scrape_configs:
 - job_name: 'springexammm'
   metrics_path: '/salutation'
   static_configs:
     - targets: ['http://192.168.100.140:8888/salutation']

# Rule files
rule_files:
  - 'alert-rules.yml'

# Alerting configurations
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
